# -*- coding: utf-8 -*-
"""Inventory_Management_Software.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTLNvn6HrHH4mCGZGlRuT6DwHkvrN7Sp

# Inventory Management Software for a Vegan Products Store
"""







import json

# Constant defining the JSON file used for data persistence
INVENTORY = "inventory.json"





# PERSISTENCE FUNCTIONS

# FUNCTION: load data from file
def load_data(file_name):

  """
  Loads data from the JSON file if it exists,
  otherwise returns an empty dictionary.
  """

  try:
    with open(file_name, "r") as json_file:
      return json.load(json_file)
  except FileNotFoundError:
      return {"products": [], "sales": []}



# FUNCTION: save data to file
def save_data(file_name, data):

  """
  Save the current data to a JSON file.
  """

  with open(file_name, "w") as json_file:
    json.dump(data, json_file, indent=4)





# INVENTORY MANAGEMENT FUNCTIONS

# FUNCTION: add products to inventory
def add_product(inventory):
  product = input("Enter the name of the product to add to the inventory: ").strip().lower()

  while True:
    try:
      quantity = int(input("Enter the quantity of the product to add to the inventory: "))
    except ValueError:
      print("Invalid input: please enter a positive integer.")
      continue

    if quantity <= 0:
      print("The quantity must be positive.")
      continue

    break

  """
  The loop handles two cases:
  1. Product already in stock: only quantity is updated.
  2. New product: the user is also asked to enter purchase price and selling price.
  """

  # Case 1: product already in stock
  for row in inventory["products"]:
    if row["product"].lower() == product:
      row["quantity"] += quantity
      print("The product is already in stock. The specified quantity will be added to the existing stock, so you do not need to enter the purchase price or the selling price again")
      print(f"ADDED: {quantity} X {product}")
      return

  # Case 2: new product
  print("The product is not in stock. Please add the following information:")

  # Enter purchase price
  while True:
    try:
      buy_price = float(input("Purchase price: "))
      if buy_price < 0:
        print("The purchase price cannot be negative.")
        continue
      break
    except ValueError:
      print("Invalid input: please enter a decimal number in the format XX.XX.")

  # Enter selling price
  while True:
    try:
      sell_price = float(input("Selling price: "))
      if sell_price < 0:
        print("The selling price cannot be negative.")
        continue
      break
    except ValueError:
      print("Invalid input: please enter a decimal number in the format XX.XX.")

  # Update the inventory after registering either a new or an existing product
  inventory["products"].append({
      "product": product,
      "quantity": quantity,
      "purchase_price": buy_price,
      "selling_price": sell_price
  })

  # Confirmation message
  print(f"ADDED: {quantity} X {product}")
  return



# FUNCTION: display the products currently available in inventory
def list_products(inventory):
  products = inventory["products"]
  if not products:
    print("Product not present in inventory")
    return

  print("PRODUCT".ljust(15), "QUANTITY".ljust(10), "PRICE")
  for p in products:
    print(
          p["product"].ljust(15),
          str(p["quantity"]).ljust(10),
          f"€{p['selling_price']:.2f}"
          )



# FUNCTION:  register a sale
def register_sale(inventory):

  """
  Initialize the list `current_sales`, which stores the products sold during the current transaction
  and will be displayed in the final sales summary.

  Also initialize `total`, which accumulates the total revenue from the current sale.
  """

  current_sales =[]
  total = 0

  while True:

    """
    Start a loop that checks whether the product exists in the inventory.

    If the product is found, another loop verifies that the requested quantity does not exceed the available stock.
    """

    product = input("Enter the name of the product being sold: ").strip().lower()

    # Check if product in inventory
    product_row = None
    for row in inventory["products"]:
      if row["product"].lower() == product.lower():
        product_row = row
        break

    # Product not found
    if product_row is None:
      print("Product is not in the inventory")

    else:
      # Ask for the quantity only if the product exists
      while True:

        # Validate the entered quantity (3 possible cases)
        # Case 1: the input is not an integer
        try:
          quantity = int(input("Enter the quantity of the product being sold: "))
        except ValueError:
          print("Invalid input: enter a positive integer")
          continue

        # Case 2: the quantity is negative or zero
        if quantity <= 0:
          print("The quantity must be positive")
          continue

        # Case 3: the requested quantity exceeds the available stock
        if quantity > product_row["quantity"]:
          print(f"The entered quantity: {quantity}"
              f" is higher than the available stock: {product_row['quantity']}."
                "Enter a quantity less than or equal to the available stock")
          continue

        # If the quantity is valid:
        # - decrease the inventory quantity,
        # - record the sale in 'currents_sales',
        # - update the total revenue
        product_row["quantity"] -= quantity
        income = quantity * product_row["selling_price"]

        current_sales.append({
            "product": product,
            "quantity": quantity,
            "sale_gross_profit": income
        })
        total += income
        break


      # Once current sale is completed, ask whether another product should be added
      another_product = input("Add another product? (yes/no) ").strip().lower()

      # Handle invalid input
      while another_product not in ("yes", "no"):
        another_product = input("Invalid answer. Please write 'yes' or 'no': ").strip().lower()

      if another_product == "no":
        break

  # Print the final summary
  print("\nSALE RECORDED")
  for sale in current_sales:
    print(f"- {sale['quantity']} X {sale['product']}:€{sale['sale_gross_profit']:.2f}")

  print (f"Total: €{total:.2f}")

  # Update the sales section of the inventory
  inventory["sales"].extend(current_sales)



# FUNCTION: calculate profits
def profits(inventory):

  """
  Initialize the variables used to calculate gross profit (`gross_profit`) and the total cost of goods sold (`total_cost`).
  """

  gross_profit = 0
  total_cost = 0

  # Iterate through all recorded sales
  for sale in inventory["sales"]:
    product_name = sale["product"]
    quantity = sale["quantity"]
    income = sale["sale_gross_profit"]

    # Calculate gross revenue
    gross_profit += income

    # Look up the sold product in the inventory to retrieve its purchase cost
    for product in inventory["products"]:
      if product["product"].lower() == product_name.lower():
        total_cost += quantity * product["purchase_price"]
        break

  # Net profit equals gross revenue minus the cost of goods sold
  net_profit = gross_profit - total_cost
  print(f"Profit: gross = €{gross_profit:.2f} net = €{net_profit:.2f}")



# FUNCTION: list of available commands
def help_commands():
  print("""
  Available commands:
  add: add a product to the inventory
  list: list the products in the inventory
  sale: record a completed sale
  profit: display total profits
  help: display all the available commands
  exit: close the program
  """)





# MAIN FUNCTION
def main():

  """
  Define the main function, which calls the appropriate inventory management functions based on the user's command.
  """
  print("Welcome to BioMarket s.a.s. program for inventory and sales management!")
  inventory = load_data(INVENTORY)

  while True:
    command = input("Enter a command: ").lower().strip()

    if command == "add":
      add_product(inventory)

    elif command == "list":
      list_products(inventory)

    elif command == "sale":
      register_sale(inventory)

    elif command == "profit":
      profits(inventory)

    elif command == "help":
      help_commands()

    elif command == "exit":
      save_data(INVENTORY, inventory)
      print("Bye bye")
      break

    else:
      print("""Invalid command
      Available commands:
      add: add a product to the inventory
      list: list the products in the inventory
      sale: record a completed sale
      profit: display total profits
      help: display the available commands
      exit: close the program
      """)



# PROGRAM START
if __name__ == "__main__":
    main()